#!/bin/bash
# Check if the global git config exists.
if [ ! -f /root/.gitconfig ]; then
  echo "DIAG: The global configuration file does not exist"
  exit 1
fi

COMMAND=$(cat /root/.bash_history | grep "^git config" | grep "\-\-global" | grep "\-\-edit" | wc -l)
if [ $COMMAND -eq 0 ]; then
  echo "DIAG: The command to edit the global configuration was not run"
  exit 1
fi

STATUSHINTS=$(git config --global --get advice.statusHints)
if [ -z $STATUSHINTS ]; then
  echo "DIAG: advice.statusHints is not set"
  exit 1
fi

if [ $STATUSHINTS != "false" ]; then
  echo "DIAG: advice.statusHints is not set to false"
  exit 1
fi

exit 0
