#!/bin/bash
# Check if the global git config exists.
if [ ! -f /root/.gitconfig ]; then
  echo "DIAG: The global configuration file does not exist"
  exit 1
fi

COMMAND=$(cat /root/.bash_history | grep "^git config" | grep "\-\-global" | grep "\-\-add" | grep "core\.editor" | wc -l)
if [ $COMMAND -eq 0 ]; then
  echo "DIAG: The command to set the core.editor value of the global configuration was not run"
  exit 1
fi

EDITOR=$(git config --global --get core.editor)
if [ -z $EDITOR ]; then
  echo "DIAG: The default editor is not set in the global configuration"
  exit 1
fi

exit 0
